### PR TITLE
Add `dataprofiler`

### PR DESCRIPTION
**Pull request by taylorfturner**
Adding the `dataprofiler` to the list of **Text** analysis tools: 

- repo: https://github.com/capitalone/DataProfiler
- docs: https://capitalone.github.io/DataProfiler

### CODE REVIEW

**Comment by taylorfturner** [comment]
bump thx!

**Comment by taylorfturner** [comment]
bump

**Comment by taylorfturner** [comment]
Anything I can do to get this merged, @makseq?

**Comment by makseq** [comment]
@taylorfturner Sorry, but how your tool is relative to annotation and labeling?

**Comment by taylorfturner** [comment]
@makseq yeah, great question. So within this package, we have a character Convolutional Neural Network that is trained to label sensitive data (namely PII and NPI data variables).

**Comment by makseq** [comment]
Sorry, it's not directly related to labeling, can't merge it :-(

**Pull request closed without merging**
